#!/usr/bin/python

# Copyright (c) 2009 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os.path
import shutil
import sys


gyps = [ 
    'base/base.gyp', 
    'build/all.gyp',
    'build/common.gypi',
    'build/external_code.gypi',  
    'skia/skia.gyp',
    'testing/gmock.gyp',
    'testing/gtest.gyp',     
    'third_party/libjpeg/libjpeg.gyp',
    'third_party/libpng/libpng.gyp',
    'third_party/libxml/libxml.gyp',
    'third_party/libxslt/libxslt.gyp',
    'third_party/lzma_sdk/lzma_sdk.gyp',
    'third_party/modp_b64/modp_b64.gyp', 
    'third_party/sqlite/sqlite.gyp',
    'third_party/zlib/zlib.gyp', 
]


def Main(argv):
  if len(argv) != 3 or argv[1] not in ['push', 'pull']:
    print 'Usage: %s push/pull PATH_TO_CHROME' % argv[0]
    return 1

  path_to_chrome = argv[2]

  for g in gyps:
    chrome_file = os.path.join(path_to_chrome, g)
    local_file = os.path.join(os.path.dirname(argv[0]), os.path.split(g)[1])
    if argv[1] == 'push':
      print 'Copying %s to %s' % (local_file, chrome_file)
      shutil.copyfile(local_file, chrome_file)
    elif argv[1] == 'pull':
      print 'Copying %s to %s' % (chrome_file, local_file)
      shutil.copyfile(chrome_file, local_file)
    else:
      assert False

  return 0


if __name__ == '__main__':
  sys.exit(Main(sys.argv))
